### ISSUE TITLE
Could not Build Success,what's wrong?

### ISSUE THREAD

**Issue by perfectswpuboy1** [illera88/Ponce#100]
When I tried to build with VS，It's not working！
Any version is no ok！
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2118	负下标 (编译源文件 ..\..\..\Ponce\src\callbacks.cpp)	Ponce	D:\GitHub\Ponce\Ponce\include_IDA6.8\typeinf.hpp	4187	

![devenv_XNMdiLCZsj](https://user-images.githubusercontent.com/356742/54483111-54af3a00-4889-11e9-9aa0-e57561424007.png)

**Comment by perfectswpuboy1** [comment]
![Ponce_Error](https://user-images.githubusercontent.com/356742/54484228-115ec680-489d-11e9-8c30-a044c439d7a6.gif)

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

You can get the prebuilt binaries from release

Thanks for reporting.
