### ISSUE TITLE
IDA 7.0 plugins Crashed with x64_fread_SAGE.exe

### ISSUE THREAD

**Issue by perfectswpuboy1** [illera88/Ponce#101]
IDA 7.0 plugins Crashed with x64_fread_SAGE.exe.
I just step by step with the Tout.But it's not going to work property.
![Ponce_examplde3_errors__jq_转](https://user-images.githubusercontent.com/356742/54508046-39bef180-497f-11e9-96c0-3bdf97701179.gif)

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
