### ISSUE TITLE
x86_crackme_hash.exe, Dissasembling error at 0x401041, No solution found

### ISSUE THREAD

**Issue by trietptm** [illera88/Ponce#102]
I test x86_crackme_hash.exe against the latest build Ponce64.dll at https://github.com/illera88/Ponce/tree/master/latest_builds
and receive no solution.

![image](https://user-images.githubusercontent.com/526959/59483715-d74f9180-8e98-11e9-95c9-53bee8f8c930.png)

![image](https://user-images.githubusercontent.com/526959/59483735-e46c8080-8e98-11e9-86d4-a2f7c0b93aad.png)

**Comment by 0ca** [comment]
That disassembly error is weird, that should be disassembled as:
```
mov eax, ds:0x403018
```
What IDA version are you using?

**Comment by JsHuang** [comment]
> That disassembly error is weird, that should be disassembled as:
> 
> ```
> mov eax, ds:0x403018
> ```
> 
> What IDA version are you using?

using IDA Version 7.0.170914 Windows x64 (64-bit address size), get the same errors!

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
