### ISSUE TITLE
Support for IDA Free 7

### ISSUE THREAD

**Issue by Trolldemorted** [illera88/Ponce#103]
On 7.0.191002 putting the dll into /plugins causes this error in the output window:

```
LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\Ponce64.dll) error: Die angegebene Prozedur wurde nicht gefunden.
C:\Program Files\IDA Freeware 7.0\plugins\Ponce64.dll: can't load file

LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\Ponce64.dll) error: Die angegebene Prozedur wurde nicht gefunden.
C:\Program Files\IDA Freeware 7.0\plugins\Ponce64.dll: can't load file
```

Any workarounds for that?

**Comment by illera88** [comment]
Unfortunately it seems that IDA plugins do not work on IDA Free 7 :/

https://reverseengineering.stackexchange.com/questions/17632/do-ida-python-plugins-work-with-ida-free-or-only-ida-pro

I've still asked Hex-Rays about it and I'm waiting to listen from them.

I'll keep you posted

**Comment by illera88** [comment]
Hex Rays answer back:
`The 7.0 freeware is simply missing the functionality required for additional plugins. No SDK is available or planned for it.`

Sorry
