### ISSUE TITLE
Cannot open capstone error in CI built binary

### ISSUE THREAD

**Issue by jampe** [illera88/Ponce#105]
First of all, thanks a lot for putting in the effort to get github actions working in the 0.3 branch! I just tried the Linux 32bit binary and got the following error after starting the plugin (same error in 64 bit, Ida 7.4):

![image](https://user-images.githubusercontent.com/9083384/79919838-6cafa080-842f-11ea-93bb-61e1b620974b.png)

Is capstone dynamically linked or something?

Additionally, the following warning message appears when starting ida with the plugin installed:
![image](https://user-images.githubusercontent.com/9083384/79920250-142cd300-8430-11ea-840b-c87cab4a2148.png)

**Comment by illera88** [comment]
Hi @jampe,

v0.3 is in high development right now and it's not working. I'm focusing on on the windows setup to make it work again but it will take some time. 

As you saw we are putting a lot of effort on CI (it's finally working for all OSes) but it will take some more time to have Ponce back in business. 

Please bear with us.

**Comment by jampe** [comment]
Of course, I'm looking forward to integrate Ponce in my workflow again, awesome tool! Thanks guys

**Comment by illera88** [comment]
That should be fixed already. 

Let me know if you keep seeing that problem. (there are others that we are currently working on)

**Comment by jampe** [comment]
Thanks for your reply. I just retried and both bugs are fixed for me on IDA 7.4 👍

- close
