### ISSUE TITLE
Make Ponce work with ARM

### ISSUE THREAD

**Issue by illera88** [illera88/Ponce#106]
Triton v0.8 supports ARM. We should extend Ponce to support ARM binaries too.

**Comment by illera88** [comment]
It "should" be working as it is now but it needs testing

**Comment by 0ca** [comment]
I tried to debug a ARM64 program with IDA 7.1 and qemu-aarch64, it didn't work, IDA crashed.
I will try it tomorrow with IDA 7.5.
 
For future reference about how to debug ARM programs:
https://www.hex-rays.com/wp-content/uploads/2019/12/debugging_gdb_qemu.pdf

**Comment by 0ca** [comment]
It works with IDA 7.5 and qemu-aarch64.
![image](https://user-images.githubusercontent.com/5008707/82387446-10777680-9a05-11ea-8a39-d1d617dfd7bb.png)

Compiled with:
```
aarch64-linux-gnu-gcc -static fread_SAGE.c -o fread_SAGE
```
Ran with qemu:
```
qemu-aarch64 -g 1234 ./fread_SAGE
```
