### ISSUE TITLE
Build link doesn't work

### ISSUE THREAD

**Issue by LusKrew** [illera88/Ponce#118]
Where can i download the latest build for IDA 7.0? 

this link doesnt work : https://github.com/illera88/Ponce/tree/master/latest_builds

**Comment by illera88** [comment]
We still haven't update the binaries from the Release section. You can find them in the artifacts of the CI: https://github.com/illera88/Ponce/actions/runs/115490440

We are still adding some features and fixing some stuff. Please let us know if you find any bug so we can fix them

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
