### ISSUE TITLE
IDA 7.5 plugin for MAC doesn't work

### ISSUE THREAD

**Issue by singleghost2** [illera88/Ponce#119]
I downloaded the ida 7.5 plug-in from this [link](https://github.com/illera88/Ponce/actions/runs/143062471), but when I dragged the plug-in to the ida plugins directory, ida couldn't start normally, stuck there. Either deleted the plug-in, or restarted the computer cannot solve it except reinstall ida. 

Mac OS version: macOS catalina 10.15.5
IDA version: Version 7.5.200619 macOS x86_64 (64-bit address size)

**Comment by illera88** [comment]
Hi,

thanks for reporting. We are still testing v0.3 since we are not officially release it. Can you tell us what's the error that you get? 

@0ca can you test it in your MAC?

**Comment by singleghost2** [comment]
Sorry, I finally found that ida failed to start due to another plugin.
