### ISSUE TITLE
Unable to configure solver timeout from configuration

### ISSUE THREAD

**Issue by mrT4ntr4** [illera88/Ponce#122]
Hey, I've just started out with Ponce and am facing some issues regarding solver timing out for some cases after 10 seconds.  
Also I can't find any option to configure solver_timeout from the config menu.  
  
![image](https://user-images.githubusercontent.com/46223734/103262620-7aa8be80-49cb-11eb-92e4-815aa2f82b7e.png)  
IDA v7.0
Ponce v0.3

Also, Thanks for the awesome plugin!

**Comment by illera88** [comment]
Hi @mrT4ntr4,

Thanks for the report. 
You are right the default timeout for the solver is 10 seconds and there is no option to change that parameter. I'm gonna create an issue to configure the timeout on the configuration.

I hope to get some time to work on the second week of the next year.

Cheers

**Comment by illera88** [comment]
Can you test it now?

**Comment by illera88** [comment]
With the latest version of Ponce you can set an arbitrary solver timeout on Ponce's configuration. I'm gonna close this issue but let me know if it's not working for you and I'll reopen.

Cheers
