### ISSUE TITLE
IDA 7.5 plugin for Windows doesn't work

### ISSUE THREAD

**Issue by hdthky** [illera88/Ponce#123]
when i select  Edit -> Plugins -> Ponce , the setting dialog box doesn't appear. As a result, i cannot symbolize argv.
windows version:  1909 (OS Build 18363.1316)
ida version: Version 7.5.201028 Windows x64 (64-bit address size)

**Comment by illera88** [comment]
Can you please try with the latest Ponce version? Please let me know if it still does not work and I'll reopen the ticket if needed.

Thank you for reporting
