### ISSUE TITLE
Triton "addCallback" API has changed 

### ISSUE THREAD

**Issue by LJP-TW** [illera88/Ponce#124]
https://github.com/illera88/Ponce/blob/master/src/triton_logic.cpp#L191
https://github.com/illera88/Ponce/blob/master/src/triton_logic.cpp#L193

The old triton addCallback API: https://github.com/JonathanSalwan/Triton/blame/7f700f9804ec3110a9af9cfe98aad293f41ce22a/src/libtriton/includes/triton/api.hpp#L286

New Triton addCallback API:
https://github.com/JonathanSalwan/Triton/blame/1b32e67cab2a0b6e623695dcaacf627c03985a13/src/libtriton/includes/triton/api.hpp#L286

The Triton API change would cause Ponce to compile error.

**Comment by illera88** [comment]
Thank you for the heads up. I'll try to get some time this weekend and fix it.

Cheers

**Comment by illera88** [comment]
Updated. Can you test it now?

**Comment by LJP-TW** [comment]
Yeah It works :)
