### ISSUE TITLE
IDA 7.5 using Ponce v0.31 will warn "Duplicate field id 3"

### ISSUE THREAD

**Issue by 22earth** [illera88/Ponce#125]
OS: Windows 10
IDA pro: 7.5

Ponce v0.30 will be OK. Ponce.cfg has been created. Then, I close IDA pro, update Ponce to v0.31. It also works.

The warning message "Duplicate field id 3" would display when I open a new binary file without "Ponce.cfg"  in same folder.

![warning](https://user-images.githubusercontent.com/4310822/114708836-72984300-9d5e-11eb-851e-98e49c122f9a.png)

**Comment by illera88** [comment]
Thank you for reporting. Fixed on [v0.3.2](https://github.com/illera88/Ponce/releases/tag/v0.3.2)
