### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by cr3m** [illera88/Ponce#129]
The plugins crashes IDA if the hexrays plugins are not available. I thinks the check for hexrays_present in term() is needed before calling remove_hexrays_callback():

#ifdef BUILD_HEXRAYS_SUPPORT
    remove_hexrays_callback(ponce_hexrays_callback, NULL);
#endif

**Comment by illera88** [comment]
Thank you for reporting the problem!! Indeed that can be causing the crash.

I have wrapped the call to `remove_hexrays_callback` in an if clause. https://github.com/illera88/Ponce/blob/master/src/main.cpp#L177-L179
