### ISSUE TITLE
IDA Pro crash due to invalid pointer dereference

### ISSUE THREAD

**Issue by jhftss** [illera88/Ponce#132]
Blame to this commit: 
https://github.com/illera88/Ponce/commit/3bbf1c02097175c93c3f44f1ac465d1380e46d46#r91495758

Crash log:
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000032a
Exception Codes:       0x0000000000000001, 0x000000000000032a

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4409]

VM Region Info: 0x32a is not in any region.  Bytes before following region: 140737488317654
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffff7000-7fffffff8000 [    4K] r-x/r-x SM=SHM  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Ponce64.dylib                 	       0x111f60dec init() + 60
1   libida64.dylib                	       0x108e62ef1 0x108da3000 + 786161

Disasm:
__text:000000000000CDB0 ; __int64 init()
__text:000000000000CDB0                 public __Z4initv
__text:000000000000CDB0 __Z4initv       proc near
__text:000000000000CDB0                 push    rbp
__text:000000000000CDB1                 mov     rbp, rsp
__text:000000000000CDB4                 push    rbx
__text:000000000000CDB5                 sub     rsp, 18h
__text:000000000000CDB9                 mov     rax, cs:___stack_chk_guard_ptr
__text:000000000000CDC0                 mov     rax, [rax]
__text:000000000000CDC3                 mov     [rbp-10h], rax
__text:000000000000CDC7                 mov     rbx, cs:_callui_ptr
__text:000000000000CDCE                 lea     rsi, [rbp-18h]
__text:000000000000CDD2                 mov     edx, 8
__text:000000000000CDD7                 mov     edi, 34h ; '4'
__text:000000000000CDDC                 xor     eax, eax
__text:000000000000CDDE                 call    qword ptr [rbx]
__text:000000000000CDE0                 test    rax, rax
__text:000000000000CDE3                 jz      loc_CEBC
__text:000000000000CDE9                 mov     al, [rbp-18h]
__text:000000000000CDEC                 cmp     al, byte ptr 810                         <--- crashed here!!!
__text:000000000000CDF3                 jnz     short loc_CE01
__text:000000000000CDF5                 mov     cl, [rbp-16h]
__text:000000000000CDF8                 cmp     cl, byte ptr 811
__text:000000000000CDFF                 jz      short loc_CE1B

**Comment by illera88** [comment]
Thanks for reporting.

Check the latest version https://github.com/illera88/Ponce/releases/tag/v0.3.5. That should fix the shity bug.

Cheers

**Comment by jhftss** [comment]
Thanks for the quick action! 👍
