### ISSUE TITLE
Ponce v0.3.4 causing crash in IDA 7.7.220118

### ISSUE THREAD

**Issue by extf33** [illera88/Ponce#133]
I'm running IDA 7.7.220118 and Ponce v0.3.4 causes a crash.

![Screenshot 2022-12-06 111042](https://user-images.githubusercontent.com/119841155/205792309-bcf9eee8-98e7-4084-86c0-7aa1055cee68.png)

[ida-20221206-110950-23116.dmp](https://www.transfernow.net/dl/20221206wm84wdpQ)

**Comment by illera88** [comment]
That is a known issue. Can you please use Ponce v0.3.5?

https://github.com/illera88/Ponce/releases/tag/v0.3.5

I'm closing the issue but feel free to reopen if the problem persist.

Cheers
