### ISSUE TITLE
Unsupported error for every instruction

### ISSUE THREAD

**Issue by MrMati** [illera88/Ponce#134]
I am using IDA Pro 7.7.
Ponce was reporting unsupported instruction error for literally every instruction.
I changed this line:
https://github.com/illera88/Ponce/blob/5eaef2bca140a131fe8e31995d3c87940ec78f48/src/triton_logic.cpp#L63
to:
`if (tritonCtx.processing(*tritonInst) != triton::arch::NO_FAULT) {`

Original code doesn't work because `tritonCtx.processing` now returns `exception_e` whose 0 value corresponds to no error.

**Comment by illera88** [comment]
Fixed on Ponce [v0.3.6](https://github.com/illera88/Ponce/releases/tag/v0.3.6).

Thank you so much for reporting!
