### ISSUE TITLE
Show the total number of analyzed instructions

### ISSUE THREAD

**Issue by 0ca** [illera88/Ponce#29]
We could use this area to show the total number of analyzed insturctions. So the user can have feedback about what is doing Ponce.
![image](https://cloud.githubusercontent.com/assets/5008707/18369649/f7b39ed6-75db-11e6-8d84-75ce7ed1b0cd.png)

**Comment by illera88** [comment]
I've asked in the Hex-Rays forum about this but didn't hear back

**Comment by illera88** [comment]
```/// Show an address on the autoanalysis indicator.
/// The address is displayed in the form " @:12345678".
/// \param ea - linear address to display

inline void show_addr(ea_t ea) { show_auto(ea); }```
