### ISSUE TITLE
Add information to the decompiled code

### ISSUE THREAD

**Issue by 0ca** [illera88/Ponce#38]
It would be cool to color the tainted instructions in the decompiled code, but I don't know if that is possible.

We could add comments, that for sure. 

If the color is not possible we could request that functionality.

**Comment by 0ca** [comment]
Example using the hexrays callback in the C++ SDK:
http://hexblog.com/ida_pro/files/vds8.cpp

Example highlighting lines in the decompiler: 
https://www.hex-rays.com/contests/2016/hexlight/hexrays_hlight.py

**Comment by illera88** [comment]
This would be really cool
