### ISSUE TITLE
Compile the plugin for MacOS, linux

### ISSUE THREAD

**Issue by 0ca** [illera88/Ponce#39]
It would be nice to have an environment to compile the plugin for other OS.

**Comment by 0ca** [comment]
We have here the versions for MacOsX and linux for IDA 6.8 and IDA 6.9, x86 and x64:
https://github.com/illera88/Ponce/tree/master/latest_builds

They were tested in Ubuntu 14.04 and Mac OS "El Capitan".

We need to do some testing in other OS.

**Comment by C0deH4cker** [comment]
@0ca: Any plans to support older versions of IDA? I have IDA 6.6 for Mac and would love to give this a try
