### ISSUE TITLE
Opening the hex dump menu while Ponce is loaded crashes IDA 6.8

### ISSUE THREAD

**Issue by Gbps** [illera88/Ponce#49]
![image](https://cloud.githubusercontent.com/assets/5607464/18817306/f456624c-8322-11e6-8094-9bc62eed1ec2.png)

I'd like to play around with your plugin, but when I try to open the menu to symbolize the memory in debugging mode, IDA crashes. I confirmed that it's Ponce that is crashing the menu.

**Comment by illera88** [comment]
Hi,
What version of IDA are you using?

**Comment by Gbps** [comment]
Version 6.8

**Comment by Gbps** [comment]
Right clicking in the Hex-View without selecting anything does not crash, but selecting any number of hex characters crashes.

Do you want me to upload my IDA crash dump?

Thanks for the quick response!

**Comment by illera88** [comment]
We compiled the binaries for version the IDA latest version (6.95). Give us a few days to check it and adapt the plugin to work fine with IDA 6.8. 
Have you tried with a couple of binaries to confirm the bug? 

Cheers

**Comment by Gbps** [comment]
I figured that might be the issue. Our university only has licenses to IDA 6.8, so that's the only one I have access to at the moment.

I have tried:

- Using different binaries (64/32 bit)
- Using different debuggers (WinDbg, Win32)
- Using different versions of IDA (idaq, idaq64)

All had the same issue preventing me running through the basic example.

The rest of the Ponce menus seem to load fine, AFAIK.

Thanks so much for your support!

**Comment by 0ca** [comment]
You are right. In IDA 6.8 Ponce crashes when you open the popup menu in the hex dump. It is working well in IDA 6.9, so it looks like Ponce is not fully working in IDA 6.8.

We will check why and we will try to have support for IDA 6.8 and IDA 6.9. Until then you can taint memory using the popup menu in the disassembler view.

Thank you for report the bug!

**Comment by Gbps** [comment]
Perfect, I'm excited!

**Comment by Gbps** [comment]
Oops.

**Comment by 0ca** [comment]
Hi @Gbps, 

We have compiled Ponce for IDA 6.8. I tested it and it looks like is working. The hexdump menu to symbolize memory has been disabled because that functionality is not exposed in the IDA 6.8 SDK.

You can download the IDA6.8 binaries from here:
https://github.com/illera88/Ponce/tree/master/builds/PonceBuild/Win32

Reopen this issue if something is not working in your plugin.
