### ISSUE TITLE
Symbolize/Tainted Memory doesnt work in IDA 6.8

### ISSUE THREAD

**Issue by heartbleeded** [illera88/Ponce#50]
Im using IDA 6.8 and symbolize/taint works with 6.9 plugin (but crashes in Hex editor). It doesnt crash with the new plugin 6.8 version but I couldnt symbolize/taint memory (even used ctrl shift M).

![untitled](https://cloud.githubusercontent.com/assets/7350821/18925454/5ab959f2-85b4-11e6-833e-863330d6545b.png)

**Comment by 0ca** [comment]
Sorry, you are right, we disabled the action in the hexdump and in the disassembly view in the IDA 6.8 release. We will fix it right now.

**Comment by 0ca** [comment]
Fixed! Please re-download the binary from the release page:
https://github.com/illera88/Ponce/releases

But remember, you can't use the symbolize memory from the hex dump, only from the disassembly view, more info in this other issue:
https://github.com/illera88/Ponce/issues/49

**Comment by bynop** [comment]
It seems all functions can't work properly! Hope fixed as soon as possible!

**Comment by trietptm** [comment]
Even in the disassembly view, Symbolize Memory doesn't work.

![screenshot - 9_29_2016 3_39_02 pm](https://cloud.githubusercontent.com/assets/526959/18946901/1a715da2-865b-11e6-99f9-25148457f122.png)
![screenshot - 9_29_2016 3_39_40 pm](https://cloud.githubusercontent.com/assets/526959/18946900/1a6d7de0-865b-11e6-9c5f-5a48d1be12c3.png)
