### ISSUE TITLE
Symbolize Memory, Negate and inject don't work

### ISSUE THREAD

**Issue by trietptm** [illera88/Ponce#51]
I test Ponce v0.1 with IDA 6.8 in Windows and see that Symbolize Memory, Negate and inject don't work, even in the disassembler view.

![screenshot - 9_29_2016 3_39_02 pm](https://cloud.githubusercontent.com/assets/526959/18946993/7546e148-865b-11e6-9081-e11d09380ecd.png)
![screenshot - 9_29_2016 3_39_40 pm](https://cloud.githubusercontent.com/assets/526959/18946994/754999ba-865b-11e6-8e21-ae5e7f6a6762.png)

![screenshot - 9_29_2016 4_31_36 pm](https://cloud.githubusercontent.com/assets/526959/18948726/765b4f36-8662-11e6-9a8e-e93049232b04.png)

**Comment by heartbleeded** [comment]
Have you tried the new version authors posted in this https://github.com/illera88/Ponce/issues/50  ? It works well for me.

**Comment by trietptm** [comment]
@heartbleeded , I downloaded Ponce yesterday from: https://github.com/illera88/Ponce/releases

**Comment by trietptm** [comment]
@heartbleeded , I download Ponce (Ponce_x86_static_IDA68.plw, Ponce_x64_static_IDA68.p6) yesterday from https://github.com/illera88/Ponce/releases .

**Comment by illera88** [comment]
We will take a look at it ASAP.

The problem we are facing is that IDA 6.8 SDK does not have some APIs we are using to get the memory selection. 

Anyway we will fix it so 6.8 users can still enjoy Ponce. 

We are currently working in it. Stay tuned

**Comment by 0ca** [comment]
@trietptm It was yesterday when we fixed that bug and we replaced the IDA6.8 plugin with the new version. So I am not sure if you have the last one.

I tried right now, the 32 bits version:
https://github.com/illera88/Ponce/releases/download/v0.1/Ponce_x86_static_IDA68.plw (md5: fa884066a8e95e23c946ac7ded6fd471) in IDA 6.8.150428 and it is working.

I am not sure about why you can't negate or even solve the condition. Are you clicking over the condition jump? Can you describe for us the steps and the binary you are using?

Thank you very much for try Ponce ;)

**Comment by 0ca** [comment]
@trietptm about the negate I think I know what it is happening.

You executed the program one time, right? The first time the main function was detected and the arguments were automatically symbolized. And this main function had symbolic instructions, so the function was renamed to T000_main.

Then you executed it a second time, this time, the main function wasn't found (we are looking for main, _main, and other variants) so the arguments weren't symbolized. And when you arrive to that condition it wasn't a symbolic condition.

We are working to solve this. 

For now you could disable in option the Rename symbolic/tainted functions.

We had some options to solve this. The idea is to detect the main function even if it was renamed.

Thank you again for the report!

**Comment by 0ca** [comment]
Now we are ignoring our own prefix for tainted/symbolized functions, so you should have this problem.

Still we want to wipe all the color after a re execution to avoid any confusion: https://github.com/illera88/Ponce/issues/57

Thank you for the report @trietptm
