### ISSUE TITLE
On IDA 6.8: Plugin crashes when selecting in hex view

### ISSUE THREAD

**Issue by PetyrBaelish** [illera88/Ponce#52]
Official binary of plugin, IDA 6.8, x86 version:
Plugin always immediately crashes when clicking at hex view and/or selecting data in hex view.
Crash location:
08A0A2F5   8B46 50          MOV EAX,DWORD PTR DS:[ESI+50]
08A0A2F8   50               PUSH EAX
08A0A2F9   8B08             MOV ECX,DWORD PTR DS:[EAX]
08A0A2FB   FF51 40          CALL DWORD PTR DS:[ECX+40]      <===========
08A0A2FE   B8 03000000      MOV EAX,3
08A0A303   5E               POP ESI
08A0A304   5D               POP EBP
08A0A305   C2 0800          RETN 8
08A0A308   B8 07000000      MOV EAX,7
08A0A30D   5E               POP ESI
08A0A30E   5D               POP EBP
08A0A30F   C2 0800          RETN 8

**Comment by illera88** [comment]
@PetyrBaelish  When did you download the binaries? Are you using the 6.8 version? Hex view selection is can't be done since 6.8 IDA SDK does not allow it. You should taint/symbolize memory from the IDA View-A. 

cheers

**Comment by 0ca** [comment]
It looks like you are using the IDA 6.9 version.

Please download the specific 6.8 plugin:
https://github.com/illera88/Ponce/releases/download/v0.1/Ponce_x86_static_IDA68.plw
https://github.com/illera88/Ponce/releases/download/v0.1/Ponce_x64_static_IDA68.p64

Related issues:
https://github.com/illera88/Ponce/issues/49
https://github.com/illera88/Ponce/issues/50
https://github.com/illera88/Ponce/issues/51
