### ISSUE TITLE
Problem with IDA 6.8, can't symbolize memory from hex-dump

### ISSUE THREAD

**Issue by inten3s** [illera88/Ponce#62]
Try with example, but seem not work
![](http://i.imgur.com/sy54bl1.png)

**Comment by jbarg** [comment]
same problem. Why is it closed? I have the latest Ponce version installed

**Comment by 0ca** [comment]
@jbarg  in IDA 6.8 you can't use the hexdump window to symbolize memory. You need to go to the CPU disassembly window and use the context menu to do the same.
