### ISSUE TITLE
Feature Request: Assign a name to symbolized memory

### ISSUE THREAD

**Issue by stackpivot** [illera88/Ponce#64]
When symbolizing multiple memory sections, it becomes quite hard to interpret the solution.

It would be great to assign the symbolized memory sections to a name and printing this with the solution as well.
Additionally, it would be great that symbolized memory sections which do not need manipulation is printed out and somehow highlighted in the solution output as well.

**Comment by illera88** [comment]
No you can add comments to all the symbolic variables in the `Ponce Symbolic Variables` window
