### ISSUE TITLE
Building Ponce master branch fails due to linking issues

### ISSUE THREAD

**Issue by Jello** [illera88/Ponce#67]
Trying to build Ponce with Visual Studio 2013 has several errors, including issues with the build documentation.
Git lfs must be installed to check out the binaries.
You must create the VERSION_NUMBER file and then execute the version_number_update.sh script with git bash.
You must build the Triton sub-project.
After this, I get 21 linking errors with the Triton lib.
![image](https://cloud.githubusercontent.com/assets/58802/22844174/dea26f1e-efaa-11e6-9e45-d98d903df000.png)

**Comment by 0ca** [comment]
Hi, 

Could you check if in the triton project you have the file registerSpecification.cpp? All the errors are related with that file.

We will improve the instructions to compile the project. Thank you for the feedback!

**Comment by Jello** [comment]
No that file doesn't exist in the Triton project that I have checked out.

**Comment by vineetpurswani** [comment]
Yes, this happened to me as well. I just added the missing cpp files to triton project, rebuilt it and everything worked out fine from there.
