### ISSUE TITLE
Add timeouts for formula solving

### ISSUE THREAD

**Issue by illera88** [illera88/Ponce#70]

**Comment by illera88** [comment]
We should create a case that takes a long to resolve

**Comment by 0ca** [comment]
I can take this

**Comment by 0ca** [comment]
@illera88 this example took 2 minutes to solve it.
You need to run it with:
```
long_time_to_solve.exe aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

Right now we block the IDA interface while a solution is getting calculated. 

I think we should start a thread every time we want to solve a formula, and then just show to the log that the formula is being solve (maybe add an update every 10 secs "Formula still solving...").  I guess we would need 2 threads. The one doing the solving and other one monitoring the time spent and updating the log with the "still solving message".

What do you think?

**Comment by illera88** [comment]
Yes, I think that's the way to go

**Comment by illera88** [comment]
We should check how to do non blocking threads in IDA

**Comment by illera88** [comment]
add that test to the examples

**Comment by 0ca** [comment]
Added to the examples:
https://github.com/illera88/Ponce/commit/86c359484680f49a24c484630dfd6b5f11e4617f

**Comment by illera88** [comment]
There is a new function in Triton that can be used to set a timeout on the solver: https://github.com/JonathanSalwan/Triton/issues/932
