### ISSUE TITLE
Starting Trace Part Way Through

### ISSUE THREAD

**Issue by bannsec** [illera88/Ponce#71]
Starting your trace part way through execution doesn't appear to work. Example:

1. Start program normally, execute past getting of user input
2. Pause execution
3. Start Ponce
4. Make the input in memory symbolic
5. Continue Tracing

Once you continue tracing it doesn't actually propagate or symbolize variables.

**Comment by 0ca** [comment]
Hi, 
I think it's a bug but if you start Ponce before debugging it should work correctly.

Could you try that?

I will take a look the next days and fix it :)

**Comment by Owlz** [comment]
Yep. If I start ponce before debugging it works fine.

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
