### ISSUE TITLE
Symbolize Reg Has Never Worked

### ISSUE THREAD

**Issue by Owlz** [illera88/Ponce#73]
I see an option to symbolize a register. However, every single time i've tried to use that it has been grayed out. Have never seen it actually available as an option.

**Comment by 0ca** [comment]
You need to select a register of the current instruction at the disassembly view.

Did you try that?

Thanks for using the plugin ;)

**Comment by Owlz** [comment]
Ah. Ok. So the interface is what's confusing me. The way it seems for this to work would be to right click on one of the registers in the registers window, then go to symbolize. That appears to not work (grayed out). But if I click on a register in the disassembly view, then it lets me select to symbolize it.

**Comment by 0ca** [comment]
We tried to add that functionality there, but the IDA API doesn't allow it :(

**Comment by perfectswpuboy1** [comment]
I don't understand.I'm meeting the same trouble with grayed
