### ISSUE TITLE
There is no color tainted instruction and color tainted condition. 

### ISSUE THREAD

**Issue by Young-X** [illera88/Ponce#75]
When I try to solve one elf with ponce, there are some errors.

Ponce setting:
![image](https://user-images.githubusercontent.com/4388415/29493924-947a76a2-85d2-11e7-9d4b-3e1ebe3172ec.png)

Symbolize memory:
![image](https://user-images.githubusercontent.com/4388415/29493931-a818d4a6-85d2-11e7-8b5a-d0b1b734d699.png)

Result:
![image](https://user-images.githubusercontent.com/4388415/29493941-c5dda0e8-85d2-11e7-930d-a160ee0d8bd6.png)

As show in result, there is no colored tainted instructions and colored tainted condition.

Do I set mistakenly? Thanks a lot~~

**Comment by 0ca** [comment]
It looks like the real check is happening inside the `call sub_400D40`. You should see inside that function if something is tainted.

The taint/symbolic engine is not going to detect things like this:
```c
int check(char myinput)
{
  int flag = 0;
  if (myinput == 'A')  //This condition is tainted
    flag = 1
  else
    flag =- 1;
  return flag; // flag is not tainted!
}
```

I'm not sure how to solve this problem.

**Comment by 0ca** [comment]
This is not a Ponce issue, it's a limitation of concolic execution.
