### ISSUE TITLE
How do you handle PCB status in snapshots?

### ISSUE THREAD

**Issue by andreafioraldi** [illera88/Ponce#84]
Hi guys your project is very cool,
can i ask you if snapshots can work for example with file descriptors opening or brk calls?
if i want to execute with ponce a piece of code with fread on a file descriptor but this fd was opened in the debugger before that i started the symbolic engine it will works?

**Comment by 0ca** [comment]
Hi @andreafioraldi , 
Ponce snapshots don't work with file descriptors or other system resources.

In your example, you could put the snapshot before this file is open, or after the `fread` during the parsing of the data.

**Comment by andreafioraldi** [comment]
Ok thanks
