### ISSUE TITLE
Configuration window overflows screen

### ISSUE THREAD

**Issue by BitTheByte** [illera88/Ponce#93]
Configuration window is little bigger than the screen without any actual way to resize it 
![](https://i.ibb.co/QN9b2rH/Capture.png)
```
IDA Version: 6.8
OS: Windows 10 Build 1803
Screen resolution: 1366x768 
```

**Comment by BitTheByte** [comment]
As a temporarily solution i tried to remove the (not implemented) options from [formTaintWindow.hpp](https://github.com/illera88/Ponce/blob/master/Ponce/src/formTaintWindow.hpp) but i'm having hard time compiling it under VS2015 since it depends on VS2013 tool-set

**Comment by illera88** [comment]
This will be handled at https://github.com/illera88/Ponce/issues/110

Closing this ticket for now
