### ISSUE TITLE
IDA 7.0 (32bit) crashed

### ISSUE THREAD

**Issue by BitTheByte** [illera88/Ponce#94]
At first i was getting the same behavior  as #88 after renaming Ponce64.dll to ponce64.dll 
IDA `x64` successfully loaded the plugin.  
However IDA `x86` was giving this message `LoadLibrary() error: The parameter is incorrect.`    
So i tried to rename it to `ponce.dll` which works fine with the `64-bit` IDA  
However with the `32-bit` crashed as result. seems it's a compatibility issue with the `32-bit` IDA   

![Crash](https://i.ibb.co/qrBcwNV/Capture.png)

**NOTE:** IDA recognized the plugin without editing the config file. also editing the config file doesn't seem to help.
```
IDA version: 7.0.170914 Windows x64 (32-bit address size)
OS: Windows 10 Build 1803 (x64)
```

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
