### ISSUE TITLE
 i cant do successed Solving formula 

### ISSUE THREAD

**Issue by cbwang505** [illera88/Ponce#96]
i compiled the source code below,and i user the parameter "ppppp"" then  Symbolized ,but i cant do successed Solving formula
[ConsoleApplication2.zip](https://github.com/illera88/Ponce/files/2786351/ConsoleApplication2.zip)

 in (!strcmp(argv[1], "jsk")) the code disassemby address ,got the [!] No solution found : in ida output  below, how can get the correct argv[1] with  "jsk" by Solving formula use ponce?

//

#include "stdafx.h"
#include "string.h"

void success(){
	printf("success\n");
}
void failed(){
	printf("failed\n");
}
void next(char *pwd){
	if (!strcmp(pwd, "123456")){
		success();
	}
	else{
		failed();
	}
}

int _tmain(int argc, _TCHAR* argv[])
{
	
	printf("please input n\n");
	puts("this is puts\n");
	if (argc < 2)
	{
		failed();
		return 0;
	}
	if (!strcmp(argv[1], "jsk")){
		success();
	}
	else{
		failed();
	}
	return 0;

}

PDBSRC: loading symbols for 'E:\git\vsprj\ConsoleApplication2\x64\Debug\ConsoleApplication2.exe'...
PDB: using DIA dll "C:\Program Files\Common Files\Microsoft Shared\VC\msdia90.dll"
PDB: DIA interface version 9.0
PDB: using load address 13F330000
[+] Symbolizing memory from 0x3e980b to 0x3e9810. Total: 6 bytes
[+] Reanalizyng instruction at 0x13f3310e0
BP Instructions traced: 16 Symbolic instructions: 0 Symbolic conditions: 0 Time: 15 secs
BP Instructions traced: 17 Symbolic instructions: 0 Symbolic conditions: 0 Time: 24 secs
[!] Instruction symbolized at 0x13f3314e8
[!] Instruction symbolized at 0x13f3314eb
[!] Instruction symbolized at 0x13f3314ee
[+] Branch symbolized detected at 0x13f3314ee: 0x13f3314f0 or 0x13f33153f, Taken:Yes
[!] Instruction symbolized at 0x13f33153f
[!] Instruction symbolized at 0x13f331542
[!] Instruction symbolized at 0x13f331147
[!] Instruction symbolized at 0x13f331149
[+] Branch symbolized detected at 0x13f331149: 0x13f33114b or 0x13f331152, Taken:Yes
[+] Solving condition at 1
[+] Solving formula...
[!] No solution found :(

**Comment by cbwang505** [comment]
.text:000000013F3310E0 ; int __fastcall T_001_main(int argc, char **argv)
.text:000000013F3310E0 T_001_main      proc near               ; CODE XREF: main_0↑j
.text:000000013F3310E0                                         ; DATA XREF: .pdata:000000013F365024↓o
.text:000000013F3310E0
.text:000000013F3310E0 arg_0           = dword ptr  8
.text:000000013F3310E0 arg_8           = qword ptr  10h
.text:000000013F3310E0
.text:000000013F3310E0                 mov     [rsp+arg_8], rdx
.text:000000013F3310E5                 mov     [rsp+arg_0], ecx
.text:000000013F3310E9                 push    rdi
.text:000000013F3310EA                 sub     rsp, 20h
.text:000000013F3310EE                 mov     rdi, rsp
.text:000000013F3310F1                 mov     ecx, 8
.text:000000013F3310F6                 mov     eax, 0CCCCCCCCh
.text:000000013F3310FB                 rep stosd
.text:000000013F3310FD                 mov     ecx, [rsp+28h+arg_0]
.text:000000013F331101                 lea     rcx, aPleaseInputN ; "please input n\n"
.text:000000013F331108                 call    printf
.text:000000013F33110D                 lea     rcx, string     ; "this is puts\n"
.text:000000013F331114                 call    puts
.text:000000013F331119                 cmp     [rsp+28h+arg_0], 2
.text:000000013F33111E                 jge     short loc_13F331129
.text:000000013F331120                 call    failed(void)
.text:000000013F331125                 xor     eax, eax
.text:000000013F331127                 jmp     short loc_13F331159
.text:000000013F331129 ; ---------------------------------------------------------------------------
.text:000000013F331129
.text:000000013F331129 loc_13F331129:                          ; CODE XREF: T_001_main+3E↑j
.text:000000013F331129                 mov     eax, 8
.text:000000013F33112E                 imul    rax, 1
.text:000000013F331132                 lea     rdx, aJsk       ; "jsk"
.text:000000013F331139                 mov     rcx, [rsp+28h+arg_8]
.text:000000013F33113E                 mov     rcx, [rcx+rax]  ; Str1
.text:000000013F331142                 call    T_000_strcmp
.text:000000013F331147                 test    eax, eax        ; Symbolized regs: eax
.text:000000013F331149                 jnz     short loc_13F331152 ; Symbolized regs: zf
.text:000000013F33114B                 call    success(void)
.text:000000013F331150                 jmp     short loc_13F331157
.text:000000013F331152 ; ---------------------------------------------------------------------------
.text:000000013F331152
.text:000000013F331152 loc_13F331152:                          ; CODE XREF: T_001_main+69↑j
.text:000000013F331152                 call    failed(void)
.text:000000013F331157
.text:000000013F331157 loc_13F331157:                          ; CODE XREF: T_001_main+70↑j
.text:000000013F331157                 xor     eax, eax
.text:000000013F331159
.text:000000013F331159 loc_13F331159:                          ; CODE XREF: T_001_main+47↑j
.text:000000013F331159                 add     rsp, 20h
.text:000000013F33115D                 pop     rdi
.text:000000013F33115E                 retn
.text:000000013F33115E T_001_main      endp
.text:000000013F33115E


.text:000000013F3314E0 ; int __cdecl T_000_strcmp(const char *Str1, const char *Str2)
.text:000000013F3314E0 T_000_strcmp    proc near               ; CODE XREF: next(char *)+2A↑p
.text:000000013F3314E0                                         ; T_001_main+62↑p
.text:000000013F3314E0                                         ; DATA XREF: ...
.text:000000013F3314E0                 sub     rdx, rcx
.text:000000013F3314E3                 test    cl, 7
.text:000000013F3314E6                 jz      short loc_13F3314FC
.text:000000013F3314E8
.text:000000013F3314E8 comp_head_loop_begin:                   ; CODE XREF: T_000_strcmp+1A↓j
.text:000000013F3314E8                                         ; T_000_strcmp+3E↓j ...
.text:000000013F3314E8                 movzx   eax, byte ptr [rcx] ; Symbolized memory: 0x3e980b
.text:000000013F3314EB                 cmp     al, [rcx+rdx]   ; Symbolized regs: al
.text:000000013F3314EE                 jnz     short return_not_equal ; Symbolized regs: zf
.text:000000013F3314F0                 inc     rcx
.text:000000013F3314F3                 test    al, al          ; Symbolized regs: al
.text:000000013F3314F5                 jz      short return_equal ; Symbolized regs: zf
.text:000000013F3314F7                 test    cl, 7
.text:000000013F3314FA                 jnz     short comp_head_loop_begin
.text:000000013F3314FC
.text:000000013F3314FC loc_13F3314FC:                          ; CODE XREF: T_000_strcmp+6↑j
.text:000000013F3314FC                 mov     r11, 8080808080808080h
.text:000000013F331506                 mov     r10, 0FEFEFEFEFEFEFEFFh
.text:000000013F331510
.text:000000013F331510 loc_13F331510:                          ; CODE XREF: T_000_strcmp+5A↓j
.text:000000013F331510                 lea     eax, [ecx+edx]
.text:000000013F331514                 and     eax, 0FFFh
.text:000000013F331519                 cmp     eax, 0FF8h
.text:000000013F33151E                 ja      short comp_head_loop_begin
.text:000000013F331520                 mov     rax, [rcx]
.text:000000013F331523                 cmp     rax, [rcx+rdx]
.text:000000013F331527                 jnz     short comp_head_loop_begin
.text:000000013F331529                 lea     r9, [r10+rax]
.text:000000013F33152D                 not     rax
.text:000000013F331530                 add     rcx, 8
.text:000000013F331534                 and     rax, r9
.text:000000013F331537                 test    r11, rax
.text:000000013F33153A                 jz      short loc_13F331510
.text:000000013F33153C
.text:000000013F33153C return_equal:                           ; CODE XREF: T_000_strcmp+15↑j
.text:000000013F33153C                 xor     eax, eax        ; Symbolized regs: eax
.text:000000013F33153E                 retn
.text:000000013F33153F ; ---------------------------------------------------------------------------
.text:000000013F33153F
.text:000000013F33153F return_not_equal:                       ; CODE XREF: T_000_strcmp+E↑j
.text:000000013F33153F                 sbb     rax, rax        ; Symbolized regs: rax cf
.text:000000013F331542                 or      rax, 1          ; Symbolized regs: rax
.text:000000013F331546                 retn
.text:000000013F331546 T_000_strcmp    endp

**Comment by 0ca** [comment]
```
[+] Solving condition at 1
[+] Keeping condition 0
[+] Inverting condition 1
```
I think you should solve first the condition 0, that is the symbolic condition inside `strcmp`. If not it keeps the condition inside the strmp `pwd[0] == 'a'` and then it tries to solve `ret value for strcmp != 0` and it can not find any solution.
