### ISSUE TITLE
Symbolize Memory Not Working??

### ISSUE THREAD

**Issue by perfectswpuboy1** [illera88/Ponce#97]
I saw this "crackmexor_negate_and_inject" and try but it's not working?
![idaq_1fglwhefx1](https://user-images.githubusercontent.com/356742/52902344-5a920b00-324a-11e9-8255-3ea014f626dd.png)
![idaq64_mhvtq6eh3l](https://user-images.githubusercontent.com/356742/52902349-62ea4600-324a-11e9-92b1-f31503a87430.png)

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
