### ISSUE TITLE
ida 7.0.17 dont work

### ISSUE THREAD

**Issue by Sirqwit** [illera88/Ponce#99]
i have download the Ponce64.dll file and copy to plugins
and add at plugins.cfg:

Ponce                            Ponce         Ctrl+Shift+Z	0  WIN

but there arent in edit/plugins
and if i do Ctrl+Shift+Z nothing appends

what can i try to do?

**Comment by JsHuang** [comment]
using IDA 64bit works for me

**Comment by illera88** [comment]
Should be fixed on [v0.3](https://github.com/illera88/Ponce/releases/tag/v0.3).

Thanks for reporting.
